"""SIMULATED Assignment Engine envelopes. Test fixture only.

Nothing here came from the real backend. Envelopes are built to the shape in
`ROBOTX_PI_P2B1_HANDOFF.md` §6 and signed with `TEST_SIGNING_KEY`, a value
that exists only in this file and is **not** the backend's
`COMMAND_SIGNING_KEY`.

Signing uses the Pi's own `engine.sign`, so a round trip through this fixture
proves the Pi verifies what the Pi signs -- not that it matches the backend.
The canonical form itself is pinned independently by a hand-written vector in
`tests/unit/test_engine_offer.py`, and should be re-pinned against a vector
generated by the backend's `commandSigning.js` before field use.

Stop geometry reuses `tests.fixtures.task_assign`: straight synthetic legs, not
a Mapbox route. `stopType` is set to an obviously fixture-only value because
the handoff does not give its vocabulary and the Pi does not interpret it.
"""

from __future__ import annotations

import time
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional

from robotx.communication.engine import sign
from tests.fixtures.task_assign import DROP, PICKUP, path_to_drop, path_to_pickup, wire_path

TEST_SIGNING_KEY = "TEST-ONLY-not-the-backend-key-0123456789"
ROBOT_ID = "robotx-pi"


def iso(at: float) -> str:
    """ISO-8601 in the form JavaScript's `toISOString` produces."""

    return datetime.fromtimestamp(at, tz=timezone.utc).strftime("%Y-%m-%dT%H:%M:%S.") + \
        f"{int((at % 1) * 1000):03d}Z"


def stops(*, with_paths: bool = True) -> List[Dict[str, Any]]:
    now_ms = int(time.time() * 1000)
    return [
        {
            "sequence": 0, "stopType": "FIXTURE_STOP_A", "siteId": "fixture-site-a",
            "lat": PICKUP[0], "lon": PICKUP[1],
            "projectedArrivalMs": now_ms + 60_000, "departureMs": now_ms + 90_000,
            "path": wire_path(path_to_pickup()) if with_paths else [],
            "pathDistanceMeters": 78.0,
        },
        {
            "sequence": 1, "stopType": "FIXTURE_STOP_B", "siteId": "fixture-site-b",
            "lat": DROP[0], "lon": DROP[1],
            "projectedArrivalMs": now_ms + 150_000, "departureMs": now_ms + 180_000,
            "path": wire_path(path_to_drop()) if with_paths else [],
            "pathDistanceMeters": 85.0,
        },
    ]


def offer_payload(
    *,
    commitment_id: str = "c-7f3a",
    fence: Any = "42",
    task_id: Optional[str] = "T-123",
    stop_sequence: Optional[List[Dict[str, Any]]] = None,
    expiry_in_s: float = 20.0,
) -> Dict[str, Any]:
    return {
        "commitmentId": commitment_id,
        "fence": fence,
        "legId": "leg-1",
        "taskId": task_id,
        "missionPlan": None,
        "stopSequence": stops() if stop_sequence is None else stop_sequence,
        "routeReference": None,
        "payloadManifest": [],
        "requirementAcknowledgements": [],
        "energyReserveParams": None,
        "targetSoc": None,
        "offerExpiry": iso(time.time() + expiry_in_s),
    }


def envelope(
    *,
    command: str = "OFFER",
    commitment_id: str = "c-7f3a",
    fence: Any = "42",
    sequence: int = 0,
    outbox_id: str = "ob-19",
    agent_id: str = ROBOT_ID,
    payload: Any = "default",
    fence_floor: Any = None,
    authority_epoch: Any = None,
    valid_for_s: float = 30.0,
    key: Optional[str] = TEST_SIGNING_KEY,
) -> Dict[str, Any]:
    """A signed envelope. Change fields *after* calling this to model tampering."""

    if payload == "default":
        payload = offer_payload(commitment_id=commitment_id, fence=fence) if command == "OFFER" else {
            "commitmentId": commitment_id, "supersedesFence": fence, "reason": "FIXTURE"}
    raw = {
        "outboxId": outbox_id,
        "command": command,
        "commandClass": "MISSION",
        "fenceScope": "COMMITMENT",
        "agentId": agent_id,
        "commitmentId": commitment_id,
        "fence": fence,
        "authorityEpoch": authority_epoch,
        "fenceFloor": fence_floor,
        "sequence": sequence,
        "notValidAfter": iso(time.time() + valid_for_s),
        "payload": payload,
    }
    raw["signature"] = sign(raw, key.encode("utf-8")) if key else ""
    return raw
